apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-source-inmemory
  namespace: inmemory-broker
spec:
  schedule: "*/1 * * * *"
  contentType: "application/json"
  data: '{"message": "Hello world!"}'
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display