apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  namespace: inmemory-broker
  name: test-trigger
spec:
  broker: test-broker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
    uri: /