apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
  namespace: default
spec:
  consumerGroup: rblake-testing
  bootstrapServers:
    - 'rhose-loca-c--o--mmk-hbcp-irvga.bf2.kafka.rhcloud.com:443'
  topics:
    - `SET_ME`
  net:
    tls:
      enable: true
    sasl:
      enable: true
      user:
        secretKeyRef:
          name: kafka-sink-auth
          key: user
      password:
        secretKeyRef:
          name: kafka-sink-auth
          key: password
      type:
        secretKeyRef:
          name: kafka-sink-auth
          key: sasl.mechanism
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default