apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: test-integration
spec:
  flows:
    - from:
        uri: "knative:event"
        steps:
          - unmarshal:
              json: { }
          - log: "receiving event from the default broker ${body}"
          - to: log:info?showAll=true&multiLine=true

