kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: istio-ingressgateway
                port:
                  number: 80