apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: test-integration
spec:
  flows:
    - from:
        uri: "timer:update"
        parameters:
          period: 1000
        steps:
          - log: "Logging: ${body}"
          - to: "knative:event/market.btc.usdt"

