apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: test-integration
spec:
  flows:
    - from:
        uri: "timer:update"
        parameters:
          period: 5000
        steps:
          - log: "sending event to default broker"
          - set-body:
              simple: "${date:now} Example message body"
          - to: "knative:event/market"

