apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: test-integration
  namespace: test-camelk
spec:
  flows:
    - from:
        uri: knative:event
        steps:
          - to: log:info?showAll=true&multiLine=true
